version: "3.8"

services:
  auth:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=mysql+pymysql://auth_user:auth_pwd@auth-db/auth_db
      - AUTH_SECRET_KEY=change_me_in_prod
    depends_on:
      - auth-db

  health:
    build: ./health-service
    container_name: health-service
    environment:
      - DATABASE_URL=mysql+pymysql://health_user:health_pwd@health-db/health_db
      - AUTH_SECRET_KEY=change_me_in_prod
    depends_on:
      - health-db

  auth-db:
    image: mariadb:11
    environment:
      - MARIADB_ROOT_PASSWORD=rootpwd
      - MARIADB_DATABASE=auth_db
      - MARIADB_USER=auth_user
      - MARIADB_PASSWORD=auth_pwd

  health-db:
    image: mariadb:11
    environment:
      - MARIADB_ROOT_PASSWORD=rootpwd
      - MARIADB_DATABASE=health_db
      - MARIADB_USER=health_user
      - MARIADB_PASSWORD=health_pwd

networks:
  default:
    name: e-sante-net
    driver: bridge
